# Generated by Django 4.1.4 on 2023-01-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
