# Generated by Django 4.1.4 on 2023-01-28 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=100)),
                ('subtitulo', models.TextField(max_length=100)),
                ('contenido', models.TextField(max_length=3000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='entradas')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
            },
        ),
    ]
