# Generated by Django 4.1.4 on 2023-01-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_entrada_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='autor',
        ),
    ]
