# Generated by Django 4.1.4 on 2023-01-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantin',
            name='tamaño',
            field=models.CharField(max_length=200),
        ),
    ]
