# Generated by Django 4.1.4 on 2023-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_arbol_tamaño_alter_frutal_tamaño'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantin',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
