# Generated by Django 4.1.4 on 2023-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_plantin_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='frutal',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
