# Generated by Django 4.1.4 on 2023-01-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_arbol_imagen_frutal_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbol',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='frutal',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='plantin',
            name='imagen',
        ),
    ]
