# Generated by Django 4.1.4 on 2023-01-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_arbol_imagen_remove_frutal_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='frutal',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='plantin',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
