# Generated by Django 4.1.4 on 2023-01-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_arbol_precio_frutal_precio_plantin_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frutal',
            new_name='Planta',
        ),
        migrations.DeleteModel(
            name='Arbol',
        ),
        migrations.DeleteModel(
            name='Plantin',
        ),
        migrations.CreateModel(
            name='Frutal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.planta',),
        ),
        migrations.CreateModel(
            name='Arbol',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.planta',),
        ),
        migrations.CreateModel(
            name='Plantin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.planta',),
        ),
    ]
