# Generated by Django 4.1.4 on 2023-01-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_frutal_planta_delete_arbol_delete_plantin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arbol',
        ),
        migrations.DeleteModel(
            name='Frutal',
        ),
        migrations.DeleteModel(
            name='Plantin',
        ),
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('planta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.planta')),
            ],
            bases=('products.planta',),
        ),
        migrations.CreateModel(
            name='Frutal',
            fields=[
                ('planta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.planta')),
            ],
            bases=('products.planta',),
        ),
        migrations.CreateModel(
            name='Plantin',
            fields=[
                ('planta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.planta')),
            ],
            bases=('products.planta',),
        ),
    ]
