# Generated by Django 4.1.4 on 2023-01-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
