# Generated by Django 4.1.4 on 2023-01-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
