# Generated by Django 4.1.4 on 2023-01-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_planta_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'verbose_name': 'planta', 'verbose_name_plural': 'plantas'},
        ),
    ]
