# Generated by Django 4.1.4 on 2023-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_planta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'verbose_name': 'prod', 'verbose_name_plural': 'prods'},
        ),
        migrations.AlterField(
            model_name='planta',
            name='imagen',
            field=models.ImageField(upload_to='prod'),
        ),
    ]
