# Generated by Django 4.1.4 on 2023-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_planta_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'verbose_name': 'PLANTA', 'verbose_name_plural': 'PLANTA'},
        ),
        migrations.AlterField(
            model_name='planta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='PLANTA'),
        ),
    ]
