# Generated by Django 4.1.4 on 2023-01-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_planta_options_alter_planta_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'verbose_name': 'Planta', 'verbose_name_plural': 'Plantas'},
        ),
        migrations.AlterField(
            model_name='planta',
            name='imagen',
            field=models.ImageField(upload_to='PLANTA'),
        ),
    ]
